"use client"

import { Fragment, useCallback, useEffect, useMemo, useState } from "react"
import { usePathname, useRouter, useSearchParams } from "next/navigation"
import { format, formatDistanceToNowStrict } from "date-fns"
import { toast } from "sonner"
import {
  AlertTriangle,
  Ban,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CreditCard,
  Download,
  FilePlus2,
  FileText,
  Landmark,
  Loader2,
  MoreHorizontal,
  ReceiptText,
  RotateCw,
  Send,
  Undo2,
  Wallet,
} from "lucide-react"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { Switch } from "@/components/ui/switch"
import { PaymentDetailsDialog } from "@/components/admin/payment-details-dialog"
import { LoadError, PageHeader, PageShell, StatTile } from "@/components/hub/page-primitives"
import { INVOICE_KIND_LABELS, aud, periodAt, periodLabel, shiftPeriod, type InvoiceKind, type StatementLine, type TaxStatus } from "@lib/finance/money"
import { cn } from "@lib/utils"

interface Statement {
  id: string
  number: string
  status: "draft" | "sent" | "paid" | "void"
  royaltyCents: number
  gstCents: number
  withholdingCents: number
  payableCents: number
  invoiceKind: InvoiceKind
  generatedAt: string
  sentAt: string | null
  sentTo: string | null
  paidAt: string | null
  paymentReference: string | null
  stripeTransferId: string | null
  transferError: string | null
  autoGenerated: boolean
}

interface Row {
  curator: {
    id: string
    name: string
    legalName: string | null
    email: string
    isActive: boolean
    taxStatus: TaxStatus | null
    abn: string | null
    gstRegistered: boolean
    rctiAgreementAt: string | null
    payouts: "none" | "incomplete" | "pending" | "ready"
    /** Masked, from Stripe. */
    bank: string | null
  }
  points: number
  live: { royaltyCents: number; gstCents: number; withholdingCents: number; payableCents: number; invoiceKind: InvoiceKind; lines: StatementLine[] }
  issues: string[]
  statement: Statement | null
}

interface Data {
  period: string
  label: string
  monthComplete: boolean
  dueDate: string
  stripe: { ok: boolean; error?: string; fetchedAt: string }
  sources: { stripe: boolean; estimated: boolean }
  /** When the 1st-of-month job generated this month's statements. */
  autoGeneratedAt: string | null
  /** AviPrep's available Stripe balance, or null if Stripe couldn't say. */
  balanceCents: number | null
  rows: Row[]
}

/** The statement's frozen figures once generated, otherwise the live ones. */
const figures = (r: Row) => {
  const s = r.statement && r.statement.status !== "void" ? r.statement : null
  return s ?? r.live
}

function TaxChip({ c }: { c: Row["curator"] }) {
  if (!c.taxStatus) return <span className="rounded bg-warning/15 px-1.5 py-px text-[11px] font-medium text-foreground">Not set up</span>
  const label = c.taxStatus === "abn" ? (c.gstRegistered ? "ABN · GST" : "ABN") : c.taxStatus === "hobby" ? "Hobby form" : "No ABN · 47%"
  return <span className="rounded border border-border bg-muted/60 px-1.5 py-px text-[11px] font-medium text-muted-foreground">{label}</span>
}

function StatusBadge({ row }: { row: Row }) {
  const s = row.statement
  if (!s)
    return figures(row).royaltyCents > 0 ? (
      <span className="inline-flex items-center gap-1.5 text-sm text-muted-foreground">
        <span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-muted-foreground/50" />
        Not generated
      </span>
    ) : (
      <span className="text-sm text-muted-foreground">Nothing owed</span>
    )
  const map = {
    draft: { dot: "bg-warning", label: "Draft", detail: s.number },
    sent: { dot: "bg-[var(--chart-1)]", label: "Sent", detail: s.sentAt ? format(new Date(s.sentAt), "d MMM") : s.number },
    paid: { dot: "bg-success", label: s.stripeTransferId ? "Paid via Stripe" : "Paid", detail: s.paidAt ? format(new Date(s.paidAt), "d MMM") : s.number },
    void: { dot: "bg-destructive", label: "Void", detail: s.number },
  }[s.status]
  return (
    <span className="inline-flex flex-col">
      <span className="inline-flex items-center gap-1.5 text-sm font-medium text-foreground">
        <span aria-hidden="true" className={cn("h-1.5 w-1.5 rounded-full", map.dot)} />
        {map.label}
      </span>
      <span className="text-xs text-muted-foreground" data-tabular>
        {map.detail}
      </span>
    </span>
  )
}

const docHref = (row: Row, period: string, doc: "statement" | "invoice") =>
  row.statement && row.statement.status !== "void"
    ? `/api/admin/payouts/document?doc=${doc}&statementId=${row.statement.id}`
    : `/api/admin/payouts/document?doc=${doc}&period=${period}&curatorId=${row.curator.id}`

export function PayoutsContent() {
  const router = useRouter()
  const pathname = usePathname()
  const searchParams = useSearchParams()
  // Default to last month: the one that's usually being paid.
  const thisMonth = useMemo(() => periodAt(new Date()), [])
  const period = searchParams.get("period") ?? shiftPeriod(thisMonth, -1)

  const [data, setData] = useState<Data | null>(null)
  const [failed, setFailed] = useState(false)
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState<string | null>(null)
  const [showAll, setShowAll] = useState(false)
  const [open, setOpen] = useState<Set<string>>(new Set())
  const [paymentFor, setPaymentFor] = useState<{ id: string; name: string } | null>(null)
  const [paying, setPaying] = useState<Row | null>(null)
  const [paidAt, setPaidAt] = useState("")
  const [reference, setReference] = useState("")
  const [voiding, setVoiding] = useState<Row | null>(null)
  const [confirmSend, setConfirmSend] = useState(false)
  const [confirmPay, setConfirmPay] = useState(false)

  const load = useCallback(
    async (refresh = false) => {
      setLoading(true)
      try {
        const res = await fetch(`/api/admin/payouts?period=${period}${refresh ? "&refresh=1" : ""}`)
        if (!res.ok) throw new Error()
        setData(await res.json())
        setFailed(false)
      } catch {
        setFailed(true)
      } finally {
        setLoading(false)
      }
    },
    [period],
  )

  useEffect(() => {
    load()
  }, [load])

  const goTo = (p: string) => {
    const params = new URLSearchParams(searchParams.toString())
    params.set("period", p)
    router.replace(`${pathname}?${params}`, { scroll: false })
  }

  async function post(url: string, body: Record<string, unknown>, busyKey: string) {
    setBusy(busyKey)
    try {
      const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })
      const json = await res.json().catch(() => ({}))
      if (!res.ok) {
        toast.error(json.error || "That didn’t work.")
        return null
      }
      return json
    } finally {
      setBusy(null)
    }
  }

  async function generate(curatorIds?: string[]) {
    const json = await post("/api/admin/payouts", { action: "generate", period, curatorIds }, curatorIds ? `gen-${curatorIds[0]}` : "generate")
    if (!json) return
    const { created, refreshed, skipped } = json.result
    toast.success(
      [created && `${created} created`, refreshed && `${refreshed} refreshed`, skipped && `${skipped} already sent`].filter(Boolean).join(", ") || "Nothing to generate",
    )
    load()
  }

  async function payAll() {
    setConfirmPay(false)
    const json = await post("/api/admin/payouts", { action: "pay", period, statementIds: payable.map((r) => r.statement!.id) }, "pay")
    if (!json) return
    if (json.paid) toast.success(`${json.paid} payout${json.paid === 1 ? "" : "s"} sent through Stripe`)
    for (const failure of json.failures ?? []) toast.error(failure)
    load()
  }

  async function sendDrafts() {
    setConfirmSend(false)
    const json = await post("/api/admin/payouts", { action: "send", period }, "send")
    if (!json) return
    if (json.sent) toast.success(`${json.sent} statement${json.sent === 1 ? "" : "s"} sent`)
    for (const failure of json.failures ?? []) toast.error(failure)
    load()
  }

  async function statementAction(row: Row, action: string, extra: Record<string, unknown> = {}, done?: string) {
    if (!row.statement) return
    const json = await post(`/api/admin/payouts/${row.statement.id}`, { action, ...extra }, `${action}-${row.curator.id}`)
    if (json) {
      if (done) toast.success(done)
      load()
    }
  }

  if (failed && !data) return <LoadError title="Couldn't load payouts" message="Refresh to try again." />

  const rows = data?.rows ?? []
  const owed = rows.filter((r) => figures(r).royaltyCents > 0 || r.statement)
  const visible = showAll ? rows : owed
  const active = rows.filter((r) => !r.statement || r.statement.status !== "void")
  const sum = (key: "royaltyCents" | "gstCents" | "withholdingCents" | "payableCents") => active.reduce((n, r) => n + figures(r)[key], 0)
  const paid = rows.filter((r) => r.statement?.status === "paid").reduce((n, r) => n + r.statement!.payableCents, 0)
  const drafts = rows.filter((r) => r.statement?.status === "draft")
  const ungenerated = rows.filter((r) => !r.statement && r.live.royaltyCents > 0)
  const withIssues = owed.filter((r) => r.issues.length)
  // Sent, something to pay, and a Stripe account that can take it.
  const payable = rows.filter((r) => r.statement?.status === "sent" && r.statement.payableCents > 0 && r.curator.payouts === "ready")
  const payableCents = payable.reduce((n, r) => n + r.statement!.payableCents, 0)
  const awaitingSetup = rows.filter((r) => r.statement?.status === "sent" && r.statement.payableCents > 0 && r.curator.payouts !== "ready")
  const shortBalance = data?.balanceCents != null && payableCents > data.balanceCents

  const toggle = (id: string) =>
    setOpen((s) => {
      const next = new Set(s)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })

  return (
    <PageShell>
      <PageHeader title="Curator payouts" description="What each curator is owed, their statements and RCTIs, and what’s been paid.">
        <div className="flex items-center gap-1 self-start rounded-lg border border-border bg-card p-1 shadow-e1">
          <Button variant="ghost" size="icon" className="h-9 w-9" onClick={() => goTo(shiftPeriod(period, -1))} aria-label="Previous month">
            <ChevronLeft className="h-4 w-4" aria-hidden="true" />
          </Button>
          <span className="min-w-36 px-2 text-center text-sm font-semibold text-foreground" aria-live="polite">
            {periodLabel(period)}
          </span>
          <Button variant="ghost" size="icon" className="h-9 w-9" onClick={() => goTo(shiftPeriod(period, 1))} disabled={period >= thisMonth} aria-label="Next month">
            <ChevronRight className="h-4 w-4" aria-hidden="true" />
          </Button>
        </div>
      </PageHeader>

      {data && (
        <div className="-mt-3 space-y-2">
          {!data.monthComplete && (
            <p className="flex items-start gap-2 rounded-lg border border-warning/40 bg-warning/10 px-3 py-2.5 text-sm text-foreground">
              <Clock className="mt-0.5 h-4 w-4 shrink-0 text-warning" aria-hidden="true" />
              {periodLabel(period)} isn’t over yet, so these figures will keep changing. Statements are generated automatically on the 1st.
            </p>
          )}
          <p className="flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-muted-foreground">
            {data.stripe.ok ? <CheckCircle2 className="h-4 w-4 text-success" aria-hidden="true" /> : <AlertTriangle className="h-4 w-4 text-warning" aria-hidden="true" />}
            {data.stripe.ok ? `Sales from Stripe, updated ${formatDistanceToNowStrict(new Date(data.stripe.fetchedAt), { addSuffix: true })}` : data.stripe.error}
            <span aria-hidden="true">·</span>
            Paid by {format(new Date(data.dueDate), "d MMMM")}
            <span aria-hidden="true">·</span>
            {data.autoGeneratedAt
              ? `Generated automatically ${format(new Date(data.autoGeneratedAt), "d MMM, h:mm a")}`
              : data.monthComplete
                ? "Waiting for the monthly run"
                : `Generates on ${format(new Date(data.dueDate).setDate(1), "d MMMM")}`}
            {data.balanceCents != null && (
              <>
                <span aria-hidden="true">·</span>
                Stripe balance {aud(data.balanceCents)} available
              </>
            )}
          </p>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        {data ? (
          <>
            <StatTile icon={ReceiptText} label="Royalties" value={aud(sum("royaltyCents"))} detail={sum("gstCents") ? `Plus ${aud(sum("gstCents"))} GST` : "No GST"} />
            <StatTile icon={Landmark} label="Withheld for the ATO" value={aud(sum("withholdingCents"))} detail="No-ABN curators" />
            <StatTile icon={Wallet} label="To pay" value={aud(sum("payableCents"))} detail={`${owed.length} curator${owed.length === 1 ? "" : "s"}`} />
            <StatTile icon={CreditCard} label="Paid" value={aud(paid)} detail={`${rows.filter((r) => r.statement?.status === "paid").length} of ${owed.length} curators`} />
          </>
        ) : (
          [0, 1, 2, 3].map((i) => <Skeleton key={i} className="h-[88px] rounded-lg" />)
        )}
      </div>

      {/* Steps for the month */}
      {data && (
        <div className="flex flex-col gap-3 rounded-xl border border-border bg-card p-4 shadow-e1 lg:flex-row lg:items-center lg:justify-between">
          <ol className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm">
            {[
              {
                n: 1,
                label: "Generated",
                done: owed.length > 0 && ungenerated.length === 0,
                detail: ungenerated.length ? (data.monthComplete ? `${ungenerated.length} waiting` : "On the 1st") : "Automatic",
              },
              { n: 2, label: "Check details", done: withIssues.length === 0, detail: withIssues.length ? `${withIssues.length} need attention` : "All set" },
              { n: 3, label: "Preview and send", done: owed.length > 0 && drafts.length === 0 && ungenerated.length === 0, detail: drafts.length ? `${drafts.length} drafts` : "Done" },
              {
                n: 4,
                label: "Pay through Stripe",
                done: owed.length > 0 && owed.every((r) => r.statement?.status === "paid" || r.statement?.status === "void"),
                detail: awaitingSetup.length ? `${awaitingSetup.length} waiting on Stripe setup` : payable.length ? `${payable.length} ready` : "Done",
              },
            ].map((step) => (
              <li key={step.n} className="flex items-center gap-2">
                <span
                  className={cn(
                    "flex h-6 w-6 items-center justify-center rounded-full text-xs font-semibold",
                    step.done ? "bg-success/15 text-success" : "bg-muted text-muted-foreground",
                  )}
                >
                  {step.done ? <CheckCircle2 className="h-3.5 w-3.5" aria-hidden="true" /> : step.n}
                </span>
                <span>
                  <span className="font-medium text-foreground">{step.label}</span>
                  <span className="ml-1.5 text-xs text-muted-foreground">{step.detail}</span>
                </span>
              </li>
            ))}
          </ol>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" className="h-9 gap-1.5" onClick={() => load(true)} disabled={loading}>
              {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <RotateCw className="h-3.5 w-3.5" aria-hidden="true" />}
              Refresh
            </Button>
            <Button asChild variant="outline" size="sm" className="h-9 gap-1.5">
              <a href={`/api/admin/payouts/export?period=${period}`}>
                <Download className="h-3.5 w-3.5" aria-hidden="true" />
                CSV
              </a>
            </Button>
            {/* Normally the 1st-of-month run does this. Only offered if a finished month was missed. */}
            {data.monthComplete && !data.autoGeneratedAt && ungenerated.length > 0 && (
              <Button variant="outline" size="sm" className="h-9 gap-1.5" onClick={() => generate()} disabled={!!busy}>
                {busy === "generate" ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <FilePlus2 className="h-3.5 w-3.5" aria-hidden="true" />}
                Generate now
              </Button>
            )}
            {drafts.length > 0 && (
              <Button size="sm" variant={payable.length ? "outline" : "default"} className="h-9 gap-1.5" onClick={() => setConfirmSend(true)} disabled={!!busy}>
                {busy === "send" ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <Send className="h-3.5 w-3.5" aria-hidden="true" />}
                Send {drafts.length} draft{drafts.length === 1 ? "" : "s"}
              </Button>
            )}
            <Button size="sm" className="h-9 gap-1.5" onClick={() => setConfirmPay(true)} disabled={!!busy || payable.length === 0}>
              {busy === "pay" ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <Wallet className="h-3.5 w-3.5" aria-hidden="true" />}
              Pay {payable.length ? aud(payableCents) : ""} via Stripe
            </Button>
          </div>
        </div>
      )}

      <section>
        <div className="mb-3 flex items-center justify-between gap-3">
          <h2 className="text-base font-semibold text-foreground">Curators</h2>
          <label className="flex items-center gap-2 text-sm text-muted-foreground">
            <Switch checked={showAll} onCheckedChange={setShowAll} />
            Show everyone
          </label>
        </div>

        {!data ? (
          <Skeleton className="h-80 rounded-xl" />
        ) : visible.length === 0 ? (
          <div className="rounded-xl border border-dashed border-border px-4 py-12 text-center">
            <p className="font-medium text-foreground">Nobody’s owed anything for {periodLabel(period)}</p>
            <p className="mt-1 text-sm text-muted-foreground">Royalties appear once there are sales in subjects with curators’ live content.</p>
          </div>
        ) : (
          <div className={cn("overflow-hidden rounded-xl border border-border bg-card shadow-e1 transition-opacity", loading && "opacity-60")}>
            <div className="overflow-x-auto">
              <table className="w-full min-w-[960px] border-collapse text-sm">
                <thead>
                  <tr className="border-b border-border bg-muted/40 text-xs text-muted-foreground">
                    <th scope="col" className="px-4 py-2.5 text-left font-medium">
                      Curator
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-right font-medium">
                      Points
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-right font-medium">
                      Royalties
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-right font-medium">
                      GST
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-right font-medium">
                      Withheld
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-right font-medium">
                      To pay
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-left font-medium">
                      Statement
                    </th>
                    <th scope="col" className="px-3 py-2.5 text-right font-medium">
                      <span className="sr-only">Actions</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {visible.map((row) => {
                    const f = figures(row)
                    const s = row.statement
                    const isOpen = open.has(row.curator.id)
                    const drifted = s?.status === "draft" && (s.royaltyCents !== row.live.royaltyCents || s.payableCents !== row.live.payableCents)
                    const invoiceKind = s && s.status !== "void" ? s.invoiceKind : row.live.invoiceKind
                    const voided = s?.status === "void"
                    return (
                      <Fragment key={row.curator.id}>
                        <tr className={cn("border-b border-border/70 align-top transition-colors hover:bg-muted/30", voided && "opacity-60")}>
                          <td className="px-4 py-3">
                            <div className="flex items-start gap-2">
                              <button
                                type="button"
                                onClick={() => toggle(row.curator.id)}
                                aria-expanded={isOpen}
                                aria-label={`${isOpen ? "Hide" : "Show"} breakdown for ${row.curator.name}`}
                                className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                              >
                                <ChevronDown className={cn("h-4 w-4 transition-transform", isOpen && "rotate-180")} aria-hidden="true" />
                              </button>
                              <div className="min-w-0">
                                <p className="flex flex-wrap items-center gap-1.5 font-medium text-foreground">
                                  {row.curator.legalName || row.curator.name}
                                  <TaxChip c={row.curator} />
                                </p>
                                <p className="truncate text-xs text-muted-foreground">
                                  {row.curator.email}
                                  {row.curator.bank && ` · ${row.curator.bank}`}
                                </p>
                                {s?.transferError && s.status !== "paid" && (
                                  <p className="mt-1 flex items-center gap-1 text-xs font-medium text-destructive">
                                    <AlertTriangle className="h-3 w-3 shrink-0" aria-hidden="true" />
                                    {s.transferError}
                                  </p>
                                )}
                                {row.issues.length > 0 && (
                                  <button
                                    type="button"
                                    onClick={() => setPaymentFor({ id: row.curator.id, name: row.curator.name })}
                                    className="mt-1 flex items-center gap-1 text-left text-xs font-medium text-warning hover:underline"
                                  >
                                    <AlertTriangle className="h-3 w-3 shrink-0" aria-hidden="true" />
                                    {row.issues.join(" · ")}
                                  </button>
                                )}
                              </div>
                            </div>
                          </td>
                          <td className="px-3 py-3 text-right text-muted-foreground" data-tabular>
                            {row.points.toLocaleString()}
                          </td>
                          <td className="px-3 py-3 text-right text-foreground" data-tabular>
                            {aud(f.royaltyCents)}
                          </td>
                          <td className="px-3 py-3 text-right text-muted-foreground" data-tabular>
                            {f.gstCents ? aud(f.gstCents) : "–"}
                          </td>
                          <td className="px-3 py-3 text-right text-muted-foreground" data-tabular>
                            {f.withholdingCents ? `−${aud(f.withholdingCents)}` : "–"}
                          </td>
                          <td className="px-3 py-3 text-right font-semibold text-foreground" data-tabular>
                            {aud(f.payableCents)}
                            {drifted && (
                              <span className="block text-[11px] font-normal text-warning" title={`Live figure now ${aud(row.live.payableCents)}`}>
                                Figures changed
                              </span>
                            )}
                          </td>
                          <td className="px-3 py-3">
                            <StatusBadge row={row} />
                          </td>
                          <td className="px-3 py-3">
                            <div className="flex items-center justify-end gap-1">
                              <Button asChild variant="ghost" size="sm" className="h-8 gap-1 px-2 text-muted-foreground hover:text-foreground">
                                <a href={docHref(row, period, "statement")} target="_blank" rel="noopener" title="Open the statement in a new tab">
                                  <FileText className="h-3.5 w-3.5" aria-hidden="true" />
                                  Statement
                                  <span className="sr-only">(opens in a new tab)</span>
                                </a>
                              </Button>
                              {invoiceKind !== "none" && (
                                <Button asChild variant="ghost" size="sm" className="h-8 gap-1 px-2 text-muted-foreground hover:text-foreground">
                                  <a href={docHref(row, period, "invoice")} target="_blank" rel="noopener" title={`Open the ${INVOICE_KIND_LABELS[invoiceKind].toLowerCase()} in a new tab`}>
                                    <ReceiptText className="h-3.5 w-3.5" aria-hidden="true" />
                                    RCTI
                                    <span className="sr-only">(opens in a new tab)</span>
                                  </a>
                                </Button>
                              )}
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                  <Button variant="ghost" size="icon" className="h-8 w-8" aria-label={`More for ${row.curator.name}`}>
                                    {busy?.endsWith(row.curator.id) ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" /> : <MoreHorizontal className="h-4 w-4" aria-hidden="true" />}
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end" className="w-52">
                                  <DropdownMenuItem onSelect={() => setPaymentFor({ id: row.curator.id, name: row.curator.name })}>
                                    <Landmark className="mr-2 h-4 w-4" aria-hidden="true" />
                                    Payment details
                                  </DropdownMenuItem>
                                  <DropdownMenuSeparator />
                                  {data.monthComplete && (!s || s.status === "draft" || s.status === "void") && (
                                    <DropdownMenuItem onSelect={() => generate([row.curator.id])}>
                                      <FilePlus2 className="mr-2 h-4 w-4" aria-hidden="true" />
                                      {s?.status === "draft" ? "Refresh draft with today’s points" : "Generate statement"}
                                    </DropdownMenuItem>
                                  )}
                                  {s && s.status !== "void" && (
                                    <DropdownMenuItem onSelect={() => statementAction(row, "send", {}, s.sentAt ? "Sent again" : "Sent")}>
                                      <Send className="mr-2 h-4 w-4" aria-hidden="true" />
                                      {s.sentAt ? "Send again" : "Send"}
                                    </DropdownMenuItem>
                                  )}
                                  {s?.status === "sent" && s.payableCents > 0 && (
                                    <DropdownMenuItem
                                      disabled={row.curator.payouts !== "ready"}
                                      onSelect={() => statementAction(row, "pay", {}, `Paid ${aud(s.payableCents)} through Stripe`)}
                                    >
                                      <Wallet className="mr-2 h-4 w-4" aria-hidden="true" />
                                      {row.curator.payouts === "ready" ? `Pay ${aud(s.payableCents)} via Stripe` : "Waiting on Stripe setup"}
                                    </DropdownMenuItem>
                                  )}
                                  {s && (s.status === "sent" || s.status === "draft") && (
                                    <DropdownMenuItem
                                      onSelect={() => {
                                        setPaidAt(new Date().toISOString().slice(0, 10))
                                        setReference(`AviPrep ${s.number}`.slice(0, 18))
                                        setPaying(row)
                                      }}
                                    >
                                      <CheckCircle2 className="mr-2 h-4 w-4" aria-hidden="true" />
                                      Mark paid outside Stripe
                                    </DropdownMenuItem>
                                  )}
                                  {s?.status === "paid" && !s.stripeTransferId && (
                                    <DropdownMenuItem onSelect={() => statementAction(row, "mark-unpaid", {}, "Marked unpaid")}>
                                      <Undo2 className="mr-2 h-4 w-4" aria-hidden="true" />
                                      Mark unpaid
                                    </DropdownMenuItem>
                                  )}
                                  {s && s.status !== "void" && s.status !== "paid" && (
                                    <>
                                      <DropdownMenuSeparator />
                                      <DropdownMenuItem className="text-destructive focus:text-destructive" onSelect={() => setVoiding(row)}>
                                        <Ban className="mr-2 h-4 w-4" aria-hidden="true" />
                                        Void statement
                                      </DropdownMenuItem>
                                    </>
                                  )}
                                </DropdownMenuContent>
                              </DropdownMenu>
                            </div>
                          </td>
                        </tr>
                        {isOpen && (
                          <tr className="border-b border-border bg-muted/20">
                            <td colSpan={8} className="px-4 py-4 sm:pl-12">
                              {row.live.lines.length === 0 ? (
                                <p className="text-sm text-muted-foreground">No live content in subjects that sold this month.</p>
                              ) : (
                                <table className="w-full max-w-3xl text-sm">
                                  <caption className="mb-2 text-left text-xs text-muted-foreground">
                                    Live breakdown. {s && s.status !== "void" ? "The statement keeps the figures from when it was generated." : ""}
                                  </caption>
                                  <thead>
                                    <tr className="text-xs text-muted-foreground">
                                      <th scope="col" className="py-1.5 text-left font-medium">Subject</th>
                                      <th scope="col" className="py-1.5 text-right font-medium">Net revenue</th>
                                      <th scope="col" className="py-1.5 text-right font-medium">Pool (25%)</th>
                                      <th scope="col" className="py-1.5 text-right font-medium">Points</th>
                                      <th scope="col" className="py-1.5 text-right font-medium">Share</th>
                                      <th scope="col" className="py-1.5 text-right font-medium">Royalty</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {row.live.lines.map((l) => (
                                      <tr key={l.subjectId} className="border-t border-border/60">
                                        <td className="py-1.5 text-foreground">{l.name}</td>
                                        <td className="py-1.5 text-right text-muted-foreground" data-tabular>{aud(l.netCents)}</td>
                                        <td className="py-1.5 text-right text-muted-foreground" data-tabular>{aud(l.poolCents)}</td>
                                        <td className="py-1.5 text-right text-muted-foreground" data-tabular>
                                          {l.myPoints.toLocaleString()} of {l.totalPoints.toLocaleString()}
                                        </td>
                                        <td className="py-1.5 text-right text-muted-foreground" data-tabular>{l.sharePercent.toFixed(2)}%</td>
                                        <td className="py-1.5 text-right font-medium text-foreground" data-tabular>{aud(l.royaltyCents)}</td>
                                      </tr>
                                    ))}
                                  </tbody>
                                </table>
                              )}
                              {s?.sentTo && (
                                <p className="mt-3 text-xs text-muted-foreground">
                                  Sent to {s.sentTo} {s.sentAt && formatDistanceToNowStrict(new Date(s.sentAt), { addSuffix: true })}
                                  {s.paymentReference && ` · Payment reference ${s.paymentReference}`}
                                </p>
                              )}
                            </td>
                          </tr>
                        )}
                      </Fragment>
                    )
                  })}
                </tbody>
                <tfoot>
                  <tr className="border-t-2 border-foreground/80">
                    <th scope="row" className="px-4 py-3 text-left font-semibold text-foreground">
                      Total
                    </th>
                    <td className="px-3 py-3" />
                    <td className="px-3 py-3 text-right font-semibold text-foreground" data-tabular>{aud(sum("royaltyCents"))}</td>
                    <td className="px-3 py-3 text-right font-semibold text-foreground" data-tabular>{aud(sum("gstCents"))}</td>
                    <td className="px-3 py-3 text-right font-semibold text-foreground" data-tabular>{sum("withholdingCents") ? `−${aud(sum("withholdingCents"))}` : "–"}</td>
                    <td className="px-3 py-3 text-right font-semibold text-foreground" data-tabular>{aud(sum("payableCents"))}</td>
                    <td colSpan={2} className="px-3 py-3 text-xs text-muted-foreground">
                      Voided statements aren’t counted
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        )}
      </section>

      <PaymentDetailsDialog curator={paymentFor} open={!!paymentFor} onOpenChange={(o) => !o && setPaymentFor(null)} onSaved={() => load()} />

      <Dialog open={!!paying} onOpenChange={(o) => !o && setPaying(null)}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Mark as paid outside Stripe</DialogTitle>
            <DialogDescription>
              {paying && `${aud(figures(paying).payableCents)} to ${paying.curator.legalName || paying.curator.name}${paying.curator.bank ? `, ${paying.curator.bank}` : ""}.`}
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-2 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label htmlFor="paid-at">Paid on</Label>
              <Input id="paid-at" type="date" className="h-10" value={paidAt} onChange={(e) => setPaidAt(e.target.value)} />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="paid-ref">Reference</Label>
              <Input id="paid-ref" className="h-10" value={reference} maxLength={120} onChange={(e) => setReference(e.target.value)} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" className="h-10" onClick={() => setPaying(null)}>
              Cancel
            </Button>
            <Button
              className="h-10"
              onClick={() => {
                const row = paying!
                setPaying(null)
                statementAction(row, "mark-paid", { paidAt, reference }, "Marked paid")
              }}
            >
              Mark paid
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={confirmPay} onOpenChange={setConfirmPay}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              Pay {aud(payableCents)} to {payable.length} curator{payable.length === 1 ? "" : "s"}?
            </AlertDialogTitle>
            <AlertDialogDescription asChild>
              <div className="space-y-3 text-sm text-muted-foreground">
                <p>Each amount is transferred from AviPrep’s Stripe balance to the curator’s Stripe account, then paid out to their bank. Transfers can’t be undone from here.</p>
                <ul className="divide-y divide-border rounded-lg border border-border">
                  {payable.map((r) => (
                    <li key={r.curator.id} className="flex items-center justify-between gap-3 px-3 py-2">
                      <span className="truncate text-foreground">{r.curator.legalName || r.curator.name}</span>
                      <span className="shrink-0 font-medium text-foreground" data-tabular>
                        {aud(r.statement!.payableCents)}
                      </span>
                    </li>
                  ))}
                </ul>
                {data?.balanceCents != null && (
                  <p className={cn(shortBalance && "font-medium text-destructive")}>
                    Available in Stripe: {aud(data.balanceCents)}.{shortBalance && " That isn’t enough for all of these, so some will fail."}
                  </p>
                )}
                {awaitingSetup.length > 0 && (
                  <p>
                    {awaitingSetup.length} more {awaitingSetup.length === 1 ? "curator hasn’t" : "curators haven’t"} finished Stripe setup, so they’ll be paid later.
                  </p>
                )}
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Not yet</AlertDialogCancel>
            <AlertDialogAction onClick={payAll}>Pay through Stripe</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <AlertDialog open={confirmSend} onOpenChange={setConfirmSend}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Send {drafts.length} statement{drafts.length === 1 ? "" : "s"}?</AlertDialogTitle>
            <AlertDialogDescription>
              Each curator gets an email with their statement{drafts.some((d) => d.statement?.invoiceKind !== "none") ? " and RCTI" : ""} attached. Preview any of them first from the table.
              {withIssues.some((r) => r.statement?.status === "draft") && " Some curators still have missing details."}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Not yet</AlertDialogCancel>
            <AlertDialogAction onClick={sendDrafts}>Send</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <AlertDialog open={!!voiding} onOpenChange={(o) => !o && setVoiding(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Void {voiding?.statement?.number}?</AlertDialogTitle>
            <AlertDialogDescription>
              {voiding?.statement?.sentAt
                ? "It’s already been sent, so let them know it’s been replaced. You can then generate a new statement with a new number."
                : "You can generate a new statement afterwards."}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Keep it</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-white hover:bg-destructive/90"
              onClick={() => {
                const row = voiding!
                setVoiding(null)
                statementAction(row, "void", {}, "Statement voided")
              }}
            >
              Void
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </PageShell>
  )
}
