import { NextResponse, type NextRequest } from "next/server"
import { prisma } from "@lib/prisma"
import { isResponse, requireStaff } from "@lib/staff"
import { computePeriod, generateStatements, isPeriod } from "@lib/finance/payouts"
import { sendStatement } from "@lib/finance/send"
import { availableBalance, payStatement, payoutAccountStatus } from "@lib/finance/connect"
import { jobKey } from "@lib/finance/monthly"
import { jobFinishedAt } from "@lib/jobs"
import { formatAbn } from "@lib/finance/money"

export const dynamic = "force-dynamic"

/** What each curator is owed for ?period=2026-09, with any statements already made. */
export async function GET(request: NextRequest) {
  const staff = await requireStaff()
  if (isResponse(staff)) return staff

  const period = request.nextUrl.searchParams.get("period")
  if (!isPeriod(period)) return NextResponse.json({ error: "Choose a month." }, { status: 400 })

  try {
    const data = await computePeriod(period, { refresh: request.nextUrl.searchParams.get("refresh") === "1" })
    if (!data) return NextResponse.json({ error: "Choose a month." }, { status: 400 })
    const [autoGeneratedAt, balanceCents] = await Promise.all([jobFinishedAt(jobKey(period)), availableBalance()])

    return NextResponse.json({
      period: data.period,
      label: data.label,
      monthComplete: data.monthComplete,
      dueDate: data.dueDate,
      stripe: data.stripe,
      sources: data.sources,
      autoGeneratedAt,
      balanceCents,
      rows: data.rows.map((r) => ({
        curator: {
          id: r.curator.id,
          name: `${r.curator.firstName} ${r.curator.lastName}`.trim(),
          legalName: r.curator.legalName,
          email: r.curator.email,
          isActive: r.curator.isActive,
          taxStatus: r.curator.taxStatus,
          abn: r.curator.abn ? formatAbn(r.curator.abn) : null,
          gstRegistered: !!r.curator.gstRegistered,
          rctiAgreementAt: r.curator.rctiAgreementAt,
          payouts: payoutAccountStatus(r.curator),
          identityVerified: r.curator.identityStatus === "verified",
          bank: r.curator.stripeBankLast4 ? `${r.curator.stripeBankName ? `${r.curator.stripeBankName} ` : ""}•••• ${r.curator.stripeBankLast4}` : null,
        },
        points: r.points,
        live: {
          royaltyCents: r.totals.royaltyCents,
          gstCents: r.totals.gstCents,
          withholdingCents: r.totals.withholdingCents,
          payableCents: r.totals.payableCents,
          invoiceKind: r.totals.invoiceKind,
          lines: r.totals.lines,
        },
        issues: r.issues,
        statement: r.statement,
      })),
    })
  } catch (error) {
    console.error("Payouts error:", error)
    return NextResponse.json({ error: "Couldn't work out payouts." }, { status: 500 })
  }
}

/**
 * { action: "generate", period, curatorIds? }  refresh draft statements (the 1st-of-month job makes them)
 * { action: "send", period, statementIds? }     email drafts (all drafts for the month if none given)
 * { action: "pay", period, statementIds? }      pay sent statements through Stripe
 */
export async function POST(request: NextRequest) {
  const staff = await requireStaff()
  if (isResponse(staff)) return staff

  const body = await request.json().catch(() => ({}))
  if (!isPeriod(body.period)) return NextResponse.json({ error: "Choose a month." }, { status: 400 })
  const ids = (value: unknown) => (Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : undefined)

  try {
    if (body.action === "generate") {
      const result = await generateStatements(body.period, staff, ids(body.curatorIds))
      return NextResponse.json({ result })
    }

    if (body.action === "pay") {
      const statementIds = ids(body.statementIds)
      const due = await prisma.royaltyStatement.findMany({
        where: { period: body.period, status: "sent", payableCents: { gt: 0 }, ...(statementIds ? { id: { in: statementIds } } : {}) },
        select: { id: true },
      })
      let paid = 0
      const failures: string[] = []
      for (const d of due) {
        const result = await payStatement(d.id)
        if (result.ok) paid += 1
        else failures.push(result.error ?? "Failed")
      }
      return NextResponse.json({ paid, failures })
    }

    if (body.action === "send") {
      const statementIds = ids(body.statementIds)
      const drafts = await prisma.royaltyStatement.findMany({
        where: { period: body.period, status: "draft", ...(statementIds ? { id: { in: statementIds } } : {}) },
        select: { id: true },
      })
      let sent = 0
      const failures: string[] = []
      for (const d of drafts) {
        const result = await sendStatement(d.id)
        if (result.ok) sent += 1
        else failures.push(result.error ?? "Failed")
      }
      return NextResponse.json({ sent, failures })
    }

    return NextResponse.json({ error: "Unknown action." }, { status: 400 })
  } catch (error) {
    console.error("Payout action error:", error)
    return NextResponse.json({ error: "Something went wrong. Try again." }, { status: 500 })
  }
}
